name: Continuous Integration

on:
  - push
  - pull_request

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        include:
          - operating-system: 'ubuntu-latest'
            php-version: '7.3'
            job-description: 'Ubuntu; PHP 7.3; latest-deps'

          - operating-system: 'ubuntu-latest'
            php-version: '7.3'
            composer-flags: '--prefer-lowest'
            job-description: 'Ubuntu; PHP 7.3; lowest-deps'

          - operating-system: 'ubuntu-latest'
            php-version: '7.4'
            job-description: 'Ubuntu; PHP 7.4; latest-deps'

          - operating-system: 'ubuntu-latest'
            php-version: '7.4'
            composer-flags: '--prefer-lowest'
            job-description: 'Ubuntu; PHP 7.4; lowest-deps'

          - operating-system: 'ubuntu-latest'
            php-version: '8.0'
            job-description: 'Ubuntu; PHP 8.0; latest-deps'

          - operating-system: 'ubuntu-latest'
            php-version: '8.0'
            composer-flags: '--prefer-lowest'
            job-description: 'Ubuntu; PHP 8.0; lowest-deps'

          - operating-system: 'windows-latest'
            php-version: '8.0'
            job-description: 'Windows; PHP 8.0; latest-deps'

          - operating-system: 'macos-latest'
            php-version: '8.0'
            job-description: 'MacOS; PHP 8.0; latest-deps'


    name: ${{ matrix.job-description }}

    runs-on: ${{ matrix.operating-system }}

    steps:
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}

      - name: Get Composer cache directory
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-dir)"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: composer-${{ runner.os }}-${{ matrix.php-version }}-${{ hashFiles('**/composer.*') }}-${{ matrix.composer-flags }}
          restore-keys: |
            composer-${{ runner.os }}-${{ matrix.php-version }}-${{ hashFiles('**/composer.*') }}-
            composer-${{ runner.os }}-${{ matrix.php-version }}-
            composer-${{ runner.os }}-
            composer-

      - name: Install dependencies
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 5
          max_attempts: 5
          retry_wait_seconds: 30
          command: |
            composer update --optimize-autoloader --no-interaction --ansi --no-progress --prefer-dist ${{ matrix.composer-flags }}
            composer info -D

      - name: Tests
        run: vendor/bin/phpunit --configuration phpunit.xml.dist
